# Generated by Django 4.2.9 on 2024-02-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='points_for_this_quiz',
            field=models.IntegerField(default=0),
        ),
    ]
