# Generated by Django 4.2.9 on 2024-02-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userlocation_points_for_this_quiz'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlocation',
            unique_together=set(),
        ),
    ]
