# Generated by Django 4.2.9 on 2024-02-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userlocation_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='points_for_this_quiz',
        ),
    ]
