# Generated by Django 4.2.9 on 2024-03-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userlocation_points_for_this_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(default='dark', max_length=10),
        ),
    ]
